package com.kubetrade.marketdata;

public interface Roles {

    String MARKET_DATA_SETTLEMENT_PRICE_READ = "MARKET_DATA_SETTLEMENT_PRICE_READ";
    String MARKET_DATA_SETTLEMENT_PRICE_WRITE = "MARKET_DATA_SETTLEMENT_PRICE_WRITE";
    String MARKET_DATA_SETTLEMENT_PRICE_ADMIN = "MARKET_DATA_SETTLEMENT_PRICE_ADMIN";

}
