quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Market Data API
          version: 0.0.1
          description: API for retrieving market data
          contact:
            email: techsupport@redhat.com
            name: Market Data API Support
            url: https://github.com/kubetrade
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html